In [10]:
import pandas as pd

# Считываем CSV файл с контактами из телефона
contacts_phone = pd.read_csv('contacts.csv')

# Считываем Excel файл с дополнительной информацией о контактах
contacts_excel = pd.read_excel('Выборн.xlsx', names=['name', 'tel'])

# # Объединяем данные из CSV и Excel файлов по полю 'Имя' контакта
merged_contacts = contacts_phone.merge(contacts_excel, on='Unnamed: 2', how='left')

# # Сохраняем объединенные контакты в новый CSV файл
# merged_contacts.to_csv('merged_contacts.csv', index=False)

KeyError: 'Unnamed: 2'

In [11]:
contacts_excel

                                                   name          tel
№ п/п сотр комментарии                              ФИО     Телефон
NaN        NaN                                      NaN          NaN
1          Труфанова             Берман Юлия Алексеевна  79629483909
2          Труфанова            Берулава Илья Хвичаевич  79257200622
3          Труфанова          Бубнов Константин Юрьевич  79037329714
...                                                 ...          ...
371        Титова           Чернов Александр Дмитриевич  79152243672
372        Титова            Чернет Владимир Валерьевич  79032544576
373        Титова        Григоренко Светлана Вадимовна   79263906881
374        Титова       Колесникова Мария Александровна  79629326114
375        Титова          Капустян Виктор Владимирович  79037991234

[377 rows x 2 columns]

In [5]:
contacts_phone

,Name,Given Name,Additional Name,Family Name,Yomi Name,Given Name Yomi,Additional Name Yomi,Family Name Yomi,Name Prefix,Name Suffix,...,Phone 2 - Type,Phone 2 - Value,Organization 1 - Type,Organization 1 - Name,Organization 1 - Yomi Name,Organization 1 - Title,Organization 1 - Department,Organization 1 - Symbol,Organization 1 - Location,Organization 1 - Job Description
0,Apple Hill,Apple,NaN,Hill,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Draw up studio,Draw,up,studio,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Finkont,Finkont,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HRD,HRD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Maша Фотограф,Maша,NaN,Фотограф,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
324,Юля Воробьева,Юля,NaN,Воробьева,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,Юля Дизайн Студия,Юля,Дизайн,Студия,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,Юля Ромашкан,Юля,NaN,Ромашкан,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
327,Юрий Николаевич,Юрий,NaN,Николаевич,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,Яценко Анастасия,Яценко,NaN,Анастасия,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
# import pandas as pd

# # Read CSV file
csv_file = pd.read_csv('contacts.csv')

# # Read Excel file
excel_file = pd.read_excel('Выборн.xlsx', names=['name', 'phone'])

# # Merge data based on 'name' field in CSV and 'ФИО' field in Excel

merged_data = csv_file.merge(excel_file, left_on='name', right_on='name', how='left')

# # Save the merged data to a new CSV file
# merged_data.to_csv('merged_contacts.csv', index=False)

KeyError: 'name'

In [14]:
excel_file

                                                   name        phone
№ п/п сотр комментарии                              ФИО     Телефон
NaN        NaN                                      NaN          NaN
1          Труфанова             Берман Юлия Алексеевна  79629483909
2          Труфанова            Берулава Илья Хвичаевич  79257200622
3          Труфанова          Бубнов Константин Юрьевич  79037329714
...                                                 ...          ...
371        Титова           Чернов Александр Дмитриевич  79152243672
372        Титова            Чернет Владимир Валерьевич  79032544576
373        Титова        Григоренко Светлана Вадимовна   79263906881
374        Титова       Колесникова Мария Александровна  79629326114
375        Титова          Капустян Виктор Владимирович  79037991234

[377 rows x 2 columns]